basePath: /
definitions:
  model.ProcessedData:
    properties:
      items:
        items:
          $ref: '#/definitions/model.SiteItem'
        type: array
      time:
        type: string
    type: object
  model.SiteItem:
    properties:
      duplication:
        type: string
      id:
        type: integer
      siteName:
        type: string
      siteid:
        type: string
      size:
        type: string
    type: object
host: localhost:7066
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: Top1000 站点数据查询 API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Top1000 API
  version: "1.0"
paths:
  /sites.json:
    get:
      consumes:
      - application/json
      description: 获取IYUU站点列表数据（需要配置IYUU_SIGN环境变量）
      produces:
      - application/json
      responses:
        "200":
          description: 站点列表数据
          schema: {}
        "500":
          description: 'error": "无法加载站点数据'
          schema:
            additionalProperties:
              type: string
            type: object
        "502":
          description: 'error": "未配置IYUU_SIGN环境变量'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 获取IYUU站点列表
      tags:
      - Sites
  /top1000.json:
    get:
      consumes:
      - application/json
      description: 获取Top1000站点列表数据，数据会自动更新（24小时过期）
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.ProcessedData'
        "500":
          description: 'error": "无法加载数据'
          schema:
            additionalProperties:
              type: string
            type: object
      summary: 获取Top1000站点数据
      tags:
      - Top1000
schemes:
- http
- https
swagger: "2.0"
